"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Clock } from "lucide-react";
import { usePortalData } from "@/context/PortalDataContext";
import { gradeTest, type GradeResult } from "@/lib/gradeTestApi";

export default function TestPage() {
  const { testId } = useParams<{ testId: string }>(); const router = useRouter(); const { tests } = usePortalData(); const test = tests.find((item) => item.id === testId || item.instituteTestId === testId);
  const questions = test?.questionItems ?? []; const [answers, setAnswers] = useState<(string | null)[]>(() => questions.map(() => null));
  const [seconds, setSeconds] = useState(test?.timeLimitInSeconds || (test?.duration ?? 30) * 60); const [busy, setBusy] = useState(false); const [result, setResult] = useState<GradeResult | null>(null); const [error, setError] = useState("");
  const submit = useCallback(async () => { if (!test || busy || result) return; setBusy(true); try { setResult(await gradeTest(test.instituteTestId ?? test.id, answers)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Submission failed"); } finally { setBusy(false); } }, [test, busy, result, answers]);
  useEffect(() => { if (seconds <= 0) { void submit(); return; } const timer = window.setInterval(() => setSeconds((value) => value - 1), 1000); return () => window.clearInterval(timer); }, [seconds, submit]);
  if (!test) return <div className="rounded-2xl border bg-white p-10 text-center"><h2 className="font-black">Exam not found.</h2><button onClick={() => router.push("/portal/exams")} className="mt-4 text-[#6C3CE9]">Back to exams</button></div>;
  if (!test.canAttempt && !result) return <div className="rounded-2xl border bg-white p-10 text-center"><h2 className="font-black">This exam is unavailable.</h2><button onClick={() => router.push("/portal/exams")} className="mt-4 text-[#6C3CE9]">Back to exams</button></div>;
  if (result) return <div className="mx-auto max-w-xl rounded-3xl border bg-white p-10 text-center shadow-sm"><p className="text-sm font-bold uppercase text-[#6C3CE9]">Exam submitted</p><h2 className="mt-3 text-4xl font-black">{result.score}/{result.maxScore}</h2><p className={`mt-3 font-bold ${result.passed ? "text-emerald-600" : "text-red-600"}`}>{result.passed ? "Passed" : "Needs improvement"}</p><button onClick={() => router.replace("/portal/results")} className="mt-7 rounded-xl bg-[#6C3CE9] px-5 py-3 font-bold text-white">View results</button></div>;
  return <div className="mx-auto max-w-3xl space-y-5"><header className="sticky top-20 z-10 flex items-center justify-between rounded-2xl border bg-white/95 p-5 shadow-sm backdrop-blur"><div><h2 className="font-black">{test.title}</h2><p className="text-sm text-slate-500">{questions.length} questions</p></div><span className="flex items-center gap-2 rounded-xl bg-violet-50 px-3 py-2 font-mono font-bold text-[#6C3CE9]"><Clock size={17} />{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, "0")}</span></header>{questions.map((question, index) => <section key={question.id} className="rounded-2xl border bg-white p-6 shadow-sm"><p className="font-bold">{index + 1}. {question.question}</p><div className="mt-5 space-y-3">{question.options.map((option) => <label key={option} className={`flex cursor-pointer gap-3 rounded-xl border p-4 ${answers[index] === option ? "border-violet-500 bg-violet-50" : "border-slate-200"}`}><input type="radio" name={question.id} checked={answers[index] === option} onChange={() => setAnswers((current) => current.map((value, position) => position === index ? option : value))} />{option}</label>)}</div></section>)}{error && <p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<button onClick={() => void submit()} disabled={busy} className="w-full rounded-xl bg-[#6C3CE9] py-4 font-bold text-white disabled:opacity-60">{busy ? "Submitting…" : "Submit exam"}</button></div>;
}
